#!/usr/bin/env bash

set -eu -o pipefail
shopt -s nullglob globstar

if [ -d "./electrum_chi" ]; then
    echo "Rebranding needed"
    exit 1
fi

for i in **/*.py; do
    if ./contrib/print_python_strings "$i" "nmc" \
        | grep -v 'io\.xaya\.electrum_chi' \
        | grep -v 'Electrum-CHI by the XAYA developers'; then
        echo "Rebranding needed"
        exit 1
    fi

    if ./contrib/print_python_strings "$i" "xaya" \
        | grep -v 'io\.xaya\.electrum_chi' \
        | grep -v 'electrum/tests/test_util\.py.*notxaya:' \
        | grep -v 'Electrum-CHI by the XAYA developers'; then
        echo "Rebranding needed"
        exit 1
    fi

    # Namecoin Bech32 addresses
    if ./contrib/print_python_strings "$i" "['\"]nc1"; then
        echo "Rebranding needed"
        exit 1
    fi
done

EXCEPTIONS="--exclude=check_chi_rebranding --exclude=RELEASE-NOTES --exclude-dir=.git"

if grep -r $EXCEPTIONS 'electrum_chi\.icns' ./; then
    echo "Rebranding needed"
    exit 1
fi

if grep -r $EXCEPTIONS 'electrum_chi\.ico' ./; then
    echo "Rebranding needed"
    exit 1
fi

if grep -r $EXCEPTIONS 'electrum_chi\.png' ./; then
    echo "Rebranding needed"
    exit 1
fi

exit 0
